version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
