### Create user
POST http://localhost:4000/api/users HTTP/1.1
content-type: application/json

{"user" : {
    "username": "some username",
    "email": "some@email.fr",
    "role" : "general_manager",
    "hash_password" : "password"
}}


### Delete user
DELETE http://localhost:4000/api/users/9 HTTP/1.1

### List all users
GET http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0aW1lX3RyYWNrZXIiLCJleHAiOjE3MzE5MjE2NDcsImlhdCI6MTcyOTUwMjQ0NywiaXNzIjoidGltZV90cmFja2VyIiwianRpIjoiNDQzMmFjYmEtN2RlMy00NTY5LWJhZjMtOTUxZTY4MGU1YWJhIiwibmJmIjoxNzI5NTAyNDQ2LCJzdWIiOiIyNyIsInR5cCI6ImFjY2VzcyJ9.OeRDtNAini21ssqM-n_d8_vNzzyUX4JRwWhIviJth2h7wpTZB0sf2uHwoFyNZShrWPmNmJxVQ2lZQ4gL3PnCxA

### List one user
GET http://localhost:4000/api/users/24
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0aW1lX3RyYWNrZXIiLCJleHAiOjE3MzE5MjE2NDcsImlhdCI6MTcyOTUwMjQ0NywiaXNzIjoidGltZV90cmFja2VyIiwianRpIjoiNDQzMmFjYmEtN2RlMy00NTY5LWJhZjMtOTUxZTY4MGU1YWJhIiwibmJmIjoxNzI5NTAyNDQ2LCJzdWIiOiIyNyIsInR5cCI6ImFjY2VzcyJ9.OeRDtNAini21ssqM-n_d8_vNzzyUX4JRwWhIviJth2h7wpTZB0sf2uHwoFyNZShrWPmNmJxVQ2lZQ4gL3PnCxA

POST http://localhost:4000/api/workingtimes/24 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0aW1lX3RyYWNrZXIiLCJleHAiOjE3MzE5MTgzMjQsImlhdCI6MTcyOTQ5OTEyNCwiaXNzIjoidGltZV90cmFja2VyIiwianRpIjoiYzA2YjA0MGUtYTAxNi00OTQ4LWI3YmMtMmM0NTZjNzZiMThiIiwibmJmIjoxNzI5NDk5MTIzLCJzdWIiOiIyNCIsInR5cCI6ImFjY2VzcyJ9.k03_lXa7AdJDGPZCPGrbbEICjHBxWBP27Lt3dryYFA-IyRWF0_bVCXka0GZDwg16jkLRDYmMtfhlppG_og6cnA


{"working_time" : {
    "start": "2024-10-07 06:02:00Z",
    "end": "2024-10-07 08:02:00Z"
}}

### List specific WT for a specific User
GET http://localhost:4000/api/workingtimes/2

### List working times for specific team
GET http://localhost:4000/api/workingtimes/team/23

### List WT with start and end dates
GET http://localhost:4000/api/workingtimes/1/?start=2024-10-03%2013%3A02%3A00Z&end=2024-10-10%2013%3A02%3A00Z HTTP/1.1


### Create working_time
POST http://localhost:4000/api/workingtimes/1 HTTP/1.1
content-type: application/json

{"working_time" : {
    "start": "2024-10-07 06:02:00Z",
    "end": "2024-10-07 08:02:00Z",
    "clockId" : 1   
}}


### Update working time
PUT http://localhost:4000/api/workingtimes/2 HTTP/1.1
content-type: application/json

{"working_time" : {
    "start": "2024-10-07 06:02:00Z",
    "end": "2024-10-07 08:02:00Z",
    "user_id" : "1"
}}

### Delete working time
DELETE http://localhost:4000/api/workingtimes/13 HTTP/1.1


### Create clocks
POST http://localhost:4000/api/clocks/1 HTTP/1.1
content-type: application/json

{"clock" : {
    "time": "2024-10-06 13:02:00Z",
    "status": true
}}

### Get clocks
GET http://localhost:4000/api/clocks/1 HTTP/1.1

### Update clock 
PUT http://localhost:4000/api/clocks/22 HTTP/1.1
content-type: application/json

{"clock" : {
    "status": true
}}

### Create team 
POST http://localhost:4000/api/teams HTTP/1.1
content-type: application/json

{"team" : {
    "name" : "la team",
    "user_ids" : [1, 2, 3], 
    "manager_id" : 1
}}


### List teams
GET http://localhost:4000/api/teams HTTP/1.1

### Get one team
GET http://localhost:4000/api/teams/23 HTTP/1.1

### Update team members
PUT http://localhost:4000/api/teams/15 HTTP/1.1
content-type: application/json
{"team" : {
    "user_ids" : [1, 2, 3]
}}


### Create Account and get a Token
POST http://localhost:4000/api/users/register HTTP/1.1
content-type: application/json

{"user" : {
    "username": "admin12345",
    "email": "admin12345@mail.com",
    "hash_password": "password", 
    "role" : "general_manager"
}}

### Sign in
POST http://localhost:4000/api/users/sign_in HTTP/1.1
content-type: application/json

{"user" : {
    "email": "admin12345@mail.com",
    "hash_password": "password"
}}