### Create user
POST http://localhost:4000/api/users HTTP/1.1
content-type: application/json

{"user" : {
    "username": "some username",
    "email": "some@email.fr",
    "role" : "general_manager"
}}


### Delete user
DELETE http://localhost:4000/api/users/9 HTTP/1.1

### List all users
GET http://localhost:4000/api/users

### Create working_time
POST http://localhost:4000/api/workingtimes/2 HTTP/1.1
content-type: application/json

{"working_time" : {
    "start": "2024-10-07 06:02:00Z",
    "end": "2024-10-07 08:02:00Z"
}}


### List specific WT for a specific User
GET http://localhost:4000/api/workingtimes/2

### List WT with start and end dates
GET http://localhost:4000/api/workingtimes/1/?start=2024-10-03%2013%3A02%3A00Z&end=2024-10-10%2013%3A02%3A00Z HTTP/1.1


### Create working_time
POST http://localhost:4000/api/workingtimes/1 HTTP/1.1
content-type: application/json

{"working_time" : {
    "start": "2024-10-07 06:02:00Z",
    "end": "2024-10-07 08:02:00Z",
    "clockId" : 1   
}}


### Update working time
PUT http://localhost:4000/api/workingtimes/2 HTTP/1.1
content-type: application/json

{"working_time" : {
    "start": "2024-10-07 06:02:00Z",
    "end": "2024-10-07 08:02:00Z",
    "user_id" : "1"
}}

### Delete working time
DELETE http://localhost:4000/api/workingtimes/13 HTTP/1.1


### Create clocks
POST http://localhost:4000/api/clocks/1 HTTP/1.1
content-type: application/json

{"clock" : {
    "time": "2024-10-06 13:02:00Z",
    "status": true
}}

### Get clocks
GET http://localhost:4000/api/clocks/1 HTTP/1.1

### Update clock 
PUT http://localhost:4000/api/clocks/22 HTTP/1.1
content-type: application/json

{"clock" : {
    "status": true
}}


### Create Account and get a Token
POST http://localhost:4000/api/users/register HTTP/1.1
content-type: application/json

{"user" : {
    "username": "some username",
    "email": "somdedfffedee@email.fr",
    "hash_password": "123dzd56"
}}